# This file is for actually running the Docker containers in one go.
services:
  api-gateway:
    image: ydalton/bike-api-gateway
    depends_on:
      - bike-service
      - cyclist-service
    environment:
      - BIKE_SERVICE_HOST=bike-service
      - CYCLIST_SERVICE_HOST=cyclist-service
      - TRIP_SERVICE_HOST=trip-service

  bike-service:
    image: ydalton/bike-service
    depends_on:
      - db-bike
    environment:
      - MYSQL_DB_HOST=db-bike
      - MYSQL_DB_USER=root
      - MYSQL_DB_PASS=abc123
    restart: always

  db-bike:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - db-bike:/var/lib/mysql

  cyclist-service:
    image: ydalton/cyclist-service
    depends_on:
      - db-cyclist
    environment:
      - MONGODB_HOST=db-cyclist
      - MONGODB_USER=root
      - MONGODB_PASS=t3st!!!2
    restart: always

  db-cyclist:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=t3st!!!2
    volumes:
      - db-cyclist:/data/db

  trip-service:
    image: ydalton/trip-service
    depends_on:
      - db-trip
    environment:
      - MONGODB_HOST=db-trip
      - MONGODB_USER=root
      - MONGODB_PASS=d3dhax0r
    restart: always

  db-trip:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=d3dhax0r
    volumes:
      - db-trip:/data/db

  frontend:
    image: ydalton/frontend
    depends_on:
      - api-gateway
    ports:
      - 8080:80

volumes:
  db-bike:
  db-cyclist:
  db-trip:
