server:
  port: 8083
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: bike-service
            uri: http://${BIKE_SERVICE_HOST:localhost}:8080
            predicates:
              - Path=/api/bike/**
          - id: cyclist-service
            uri: http://${CYCLIST_SERVICE_HOST:localhost}:8080
            predicates:
              - Path=/api/cyclist/**