server:
  port: 8083
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: test
            uri: http://${BIKE_SERVICE_HOST:localhost:8080}
            predicates:
              - Path=/test
              - Method=GET
            filters:
              - SetPath=/