server:
  port: 8083
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: bike-service
          uri: http://${BIKE_SERVICE_HOST:localhost}:8080
          predicates:
            - Path=/api/bike/**
        - id: cyclist-service
          uri: http://${CYCLIST_SERVICE_HOST:localhost}:8080
          predicates:
            - Path=/api/cyclist/**
        - id: trip-service
          uri: http://${TRIP_SERVICE_HOST:localhost}:8080
          predicates:
            - Path=/api/trip/**