name: Build and deploy Docker images 

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images with docker-compose
      run: docker compose -f docker-compose-build.yaml build
      env:
        VITE_OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
        GOOGLE_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH_SECRET }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Deploy the Docker images to Dockerhub
      run: docker compose -f docker-compose-build.yaml push
